import type { LegendEdge, LegendNode, Region } from "./types";

export const regions: Region[] = [
  { id: "india", label: "印度文化圈", subtitle: "INDIAN CULTURAL SPHERE", y: 80, height: 210 },
  { id: "china", label: "中国文化圈", subtitle: "CHINESE CULTURAL SPHERE", y: 290, height: 280 },
  { id: "japan", label: "日本现代传播", subtitle: "MODERN JAPAN", y: 570, height: 170 },
  { id: "modern-china", label: "中国现代传播", subtitle: "MODERN CHINA", y: 740, height: 170 },
];

export const nodes: LegendNode[] = [
  {
    id: "hanuman",
    name: "哈奴曼",
    latinName: "Hanuman",
    year: -400,
    yearLabel: "约公元前 4 世纪",
    region: "india",
    row: 0,
    kind: "origin",
    summary: "印度史诗《罗摩衍那》中的神猴形象。其与孙悟空之间的影响关系存在长期讨论，P1 仅将其作为待核验候选来源。",
    sources: [{ label: "Wikipedia · Hanuman", url: "https://en.wikipedia.org/wiki/Hanuman" }],
    isTrace: true,
  },
  {
    id: "monkey-pilgrim",
    name: "猴行者 / 取经猴形象",
    latinName: "Monkey Pilgrim",
    year: 1200,
    yearLabel: "宋元时期",
    region: "china",
    row: 1,
    kind: "origin",
    summary: "早期取经故事中的猴行者形象，是《西游记》孙悟空形成过程中的重要前身之一。",
    sources: [{ label: "Wikipedia · Journey to the West", url: "https://en.wikipedia.org/wiki/Journey_to_the_West" }],
    isTrace: true,
  },
  {
    id: "wuzhiqi",
    name: "无支祁",
    latinName: "Wuzhiqi",
    year: 1100,
    yearLabel: "宋代文献可见",
    region: "china",
    row: 0,
    kind: "origin",
    summary: "中国水怪传说中的猿猴形象。其与孙悟空的关系尚有争议，在图谱中以推测关联表示。",
    sources: [{ label: "Wikipedia · Wuzhiqi", url: "https://en.wikipedia.org/wiki/Wuzhiqi" }],
    isTrace: true,
  },
  {
    id: "sun-wukong",
    name: "孙悟空《西游记》",
    latinName: "Sun Wukong",
    year: 1592,
    yearLabel: "明代 · 约 1592",
    region: "china",
    row: 2,
    kind: "literature",
    summary: "《西游记》的核心角色。P1 以这一文学版本作为 Trace 中心，观察早期候选来源和现代改编如何汇聚与分叉。",
    sources: [
      { label: "Wikipedia · Sun Wukong", url: "https://en.wikipedia.org/wiki/Monkey_King" },
      { label: "Wikipedia · Journey to the West", url: "https://en.wikipedia.org/wiki/Journey_to_the_West" },
    ],
    isTrace: true,
  },
  {
    id: "dragon-ball",
    name: "《龙珠》孙悟空",
    latinName: "Son Goku",
    year: 1984,
    yearLabel: "1984 · 漫画",
    region: "japan",
    row: 0,
    kind: "modern",
    summary: "鸟山明《龙珠》的主角，以《西游记》孙悟空为明确灵感来源，形成全球流行文化中的新分支。",
    sources: [{ label: "Wikipedia · Son Goku", url: "https://en.wikipedia.org/wiki/Goku" }],
    isTrace: true,
  },
  {
    id: "saiyuki",
    name: "《最游记》孙悟空",
    latinName: "Saiyuki · Son Goku",
    year: 1997,
    yearLabel: "1997 · 漫画",
    region: "japan",
    row: 1,
    kind: "modern",
    summary: "峰仓和也作品《最游记》中的孙悟空版本，是《西游记》角色在日本现代漫画中的再创作。",
    sources: [{ label: "Wikipedia · Saiyuki", url: "https://en.wikipedia.org/wiki/Saiyuki_(manga)" }],
    isTrace: true,
  },
  {
    id: "a-chinese-odyssey",
    name: "《大话西游》至尊宝",
    latinName: "A Chinese Odyssey",
    year: 1995,
    yearLabel: "1995 · 电影",
    region: "modern-china",
    row: 0,
    kind: "modern",
    summary: "《大话西游》通过至尊宝 / 孙悟空重新讲述经典角色，在华语流行文化中形成广泛影响。",
    sources: [{ label: "Wikipedia · A Chinese Odyssey", url: "https://en.wikipedia.org/wiki/A_Chinese_Odyssey" }],
    isTrace: true,
  },
  {
    id: "black-myth",
    name: "《黑神话：悟空》",
    latinName: "Black Myth: Wukong",
    year: 2024,
    yearLabel: "2024 · 游戏",
    region: "modern-china",
    row: 1,
    kind: "modern",
    summary: "以《西游记》为背景的动作角色扮演游戏，是孙悟空母题在当代游戏媒介中的重要传播节点。",
    sources: [{ label: "Wikipedia · Black Myth: Wukong", url: "https://en.wikipedia.org/wiki/Black_Myth:_Wukong" }],
    isTrace: true,
  },
  {
    id: "ramayana",
    name: "《罗摩衍那》",
    latinName: "Ramayana",
    year: -300,
    yearLabel: "约公元前 3 世纪",
    region: "india",
    row: 1,
    kind: "literature",
    summary: "古印度史诗，为哈奴曼形象的重要文本来源。",
    sources: [{ label: "Wikipedia · Ramayana", url: "https://en.wikipedia.org/wiki/Ramayana" }],
    isTrace: false,
  },
  {
    id: "zaju",
    name: "《西游记》杂剧",
    latinName: "Journey to the West · Zaju",
    year: 1350,
    yearLabel: "元末明初",
    region: "china",
    row: 3,
    kind: "literature",
    summary: "在长篇小说之前，西游题材已经通过戏曲等形式持续发展。",
    sources: [{ label: "Wikipedia · Journey to the West", url: "https://en.wikipedia.org/wiki/Journey_to_the_West" }],
    isTrace: false,
  },
  {
    id: "tv-journey",
    name: "《西游记》电视剧",
    latinName: "Journey to the West · TV",
    year: 1986,
    yearLabel: "1986 · 电视剧",
    region: "modern-china",
    row: 2,
    kind: "modern",
    summary: "央视电视剧《西游记》塑造了华语观众熟悉的孙悟空荧幕形象。",
    sources: [{ label: "Wikipedia · Journey to the West (1986 TV series)", url: "https://en.wikipedia.org/wiki/Journey_to_the_West_(1986_TV_series)" }],
    isTrace: false,
  },
  {
    id: "enma",
    name: "《最游记 Reload》",
    latinName: "Saiyuki Reload",
    year: 2002,
    yearLabel: "2002 · 漫画",
    region: "japan",
    row: 2,
    kind: "modern",
    summary: "《最游记》的续作分支，用于呈现现代改编继续演化的上下文。",
    sources: [{ label: "Wikipedia · Saiyuki", url: "https://en.wikipedia.org/wiki/Saiyuki_(manga)" }],
    isTrace: false,
  },
];

export const edges: LegendEdge[] = [
  {
    id: "hanuman-to-wukong",
    from: "hanuman",
    to: "sun-wukong",
    relation: "候选影响",
    confidence: "probable",
    debated: true,
    source: { label: "Wikipedia · Monkey King", url: "https://en.wikipedia.org/wiki/Monkey_King" },
    isTrace: true,
  },
  {
    id: "wuzhiqi-to-wukong",
    from: "wuzhiqi",
    to: "sun-wukong",
    relation: "候选影响",
    confidence: "speculative",
    debated: true,
    source: { label: "Wikipedia · Wuzhiqi", url: "https://en.wikipedia.org/wiki/Wuzhiqi" },
    isTrace: true,
  },
  {
    id: "pilgrim-to-wukong",
    from: "monkey-pilgrim",
    to: "sun-wukong",
    relation: "文本演化",
    confidence: "probable",
    source: { label: "Wikipedia · Journey to the West", url: "https://en.wikipedia.org/wiki/Journey_to_the_West" },
    isTrace: true,
  },
  {
    id: "wukong-to-dragon-ball",
    from: "sun-wukong",
    to: "dragon-ball",
    relation: "明确改编",
    confidence: "confirmed",
    source: { label: "Wikipedia · Goku", url: "https://en.wikipedia.org/wiki/Goku" },
    isTrace: true,
  },
  {
    id: "wukong-to-saiyuki",
    from: "sun-wukong",
    to: "saiyuki",
    relation: "明确改编",
    confidence: "confirmed",
    source: { label: "Wikipedia · Saiyuki", url: "https://en.wikipedia.org/wiki/Saiyuki_(manga)" },
    isTrace: true,
  },
  {
    id: "wukong-to-odyssey",
    from: "sun-wukong",
    to: "a-chinese-odyssey",
    relation: "明确改编",
    confidence: "confirmed",
    source: { label: "Wikipedia · A Chinese Odyssey", url: "https://en.wikipedia.org/wiki/A_Chinese_Odyssey" },
    isTrace: true,
  },
  {
    id: "wukong-to-black-myth",
    from: "sun-wukong",
    to: "black-myth",
    relation: "明确改编",
    confidence: "confirmed",
    source: { label: "Wikipedia · Black Myth: Wukong", url: "https://en.wikipedia.org/wiki/Black_Myth:_Wukong" },
    isTrace: true,
  },
  {
    id: "ramayana-to-hanuman",
    from: "ramayana",
    to: "hanuman",
    relation: "文本来源",
    confidence: "confirmed",
    source: { label: "Wikipedia · Ramayana", url: "https://en.wikipedia.org/wiki/Ramayana" },
    isTrace: false,
  },
  {
    id: "zaju-to-wukong",
    from: "zaju",
    to: "sun-wukong",
    relation: "文本演化",
    confidence: "probable",
    source: { label: "Wikipedia · Journey to the West", url: "https://en.wikipedia.org/wiki/Journey_to_the_West" },
    isTrace: false,
  },
  {
    id: "wukong-to-tv",
    from: "sun-wukong",
    to: "tv-journey",
    relation: "明确改编",
    confidence: "confirmed",
    source: { label: "Wikipedia · Journey to the West (1986 TV series)", url: "https://en.wikipedia.org/wiki/Journey_to_the_West_(1986_TV_series)" },
    isTrace: false,
  },
  {
    id: "saiyuki-to-reload",
    from: "saiyuki",
    to: "enma",
    relation: "续作",
    confidence: "confirmed",
    source: { label: "Wikipedia · Saiyuki", url: "https://en.wikipedia.org/wiki/Saiyuki_(manga)" },
    isTrace: false,
  },
];
